org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17.19
fabric_api_version=0.155.2+26.1.2

mod_version=1.0.2
maven_group=com.itsgeorge.performanceoverlay
archives_base_name=performanceoverlay

modmenu_version=18.0.0
cloth_config_version=26.1.154+fabric
placeholder_api_version=3.0.0+26.1
basic_math_version=0.6.1

systemProp.org.gradle.internal.http.connectionTimeout=600000
systemProp.org.gradle.internal.http.socketTimeout=600000
systemProp.org.gradle.internal.repository.max.retries=10
systemProp.org.gradle.internal.repository.initial.backoff=1000
